# Usando a versão estável mais recente do Postgres
FROM postgres:latest

# (Opcional) Copia scripts SQL para rodar na criação do banco
# COPY ./init.sql /docker-entrypoint-initdb.d/

# O Dockerfile não precisa declarar as ENV fixas aqui 
# pois vamos injetá-las via Docker Compose.
